version: '3'

services:
  ze-appiandemo:
    image: dockerhub.concordservicing.com:5001/concord/universe
    environment:
      RUN_IN_TEST_MODE: "${RUN_IN_TEST_MODE}"
      CSS_USERNAME: "${CSS_USERNAME}"
      CSS_USERPASSWORD: "${CSS_USERPASSWORD}"
      CSS_ACCOUNT: "${CSS_ACCOUNT}"
      CSS_HOSTNAME: "css"
    ports:
      - "80:80"
    extra_hosts:
      - "css:${CSS_IP_ADDRESS}"
      - "css.concordservicing.com:${CSS_IP_ADDRESS}"
