version: '3'

services:
  ze-appiandemo:
    image: appiandemo
    environment:
      RUN_IN_TEST_MODE: "${RUN_IN_TEST_MODE}"
      CSS_USERNAME: "${CSS_USERNAME}"
      CSS_USERPASSWORD: "${CSS_USERPASSWORD}"
      CSS_ACCOUNT: "${CSS_ACCOUNT}"
      CSS_HOSTNAME: "${CSS_HOSTNAME}"
    ports:
      - "8080:80"
